application/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('detail/<uuid:pk>/', views.detail, name='detail'),
    path('delete/<uuid:pk>/', views.delete, name='delete'),
    path('update/<uuid:pk>/', views.update, name='update'),
]

application/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls'))
]

application/diary/models.py
import os
import uuid
import logging
from pynamodb.models import Model
from pynamodb.attributes import (
    UnicodeAttribute, UTCDateTimeAttribute
)
from django.utils import timezone

logging.basicConfig()
log = logging.getLogger("pynamodb")
log.setLevel(logging.DEBUG)
log.propagate = True


class Day(Model):
    class Meta:
        table_name = "Day"
        # host = "http://localhost:8000"
        host = "http://dynamodb:8000"
        region = 'ap-northeast-1'
        write_capacity_units = 1
        read_capacity_units = 1
        aws_access_key_id = os.environ.get('ACCESS_KEY')
        aws_secret_access_key = os.environ.get('SECRET_ACCESS_KEY')

    id = UnicodeAttribute(hash_key=True, default=str(uuid.uuid4()))
    title = UnicodeAttribute()
    text = UnicodeAttribute()
    created_at = UTCDateTimeAttribute(default=timezone.now())
    updated_at = UTCDateTimeAttribute(default=timezone.now())

    def __str__(self):
        return self.title

application/diary/forms.py
from django import forms
from .models import Day


class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__'

application/diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.http import QueryDict
from .models import Day
import uuid


def index(request):
    """
    Index
    """
    day_list = Day.scan()
    context = {
        'day_list': day_list
    }
    return render(request, 'diary/day_list.html', context)


def add(request):
    """
    Itemの追加
    """
    if request.method == 'POST':
        response_dict = QueryDict(request.body)
        save_data = Day(
            str(uuid.uuid4()),
            title=response_dict['title'],
            text=response_dict['text'],
            created_at=timezone.now(),
            updated_at=timezone.now()
        )
        save_data.save()
        return redirect('diary:index')

    return render(request, 'diary/day_form.html')


def update(request, pk):
    """
    Itemの更新
    """
    day = Day.get(str(pk))
    if request.method == 'POST':
        response_dict = QueryDict(request.body)
        day.update(actions=[
            Day.title.set(response_dict['title']),
            Day.text.set(response_dict['text']),
            Day.updated_at.set(timezone.now())
        ])
        return redirect('diary:index')

    context = {
        'day': day
    }
    return render(request, 'diary/day_form.html', context)


def delete(request, pk):
    """
    Itemの削除
    """
    day = Day.get(str(pk))

    if request.method == 'POST':
        day.delete()
        return redirect('diary:index')

    context = {
        'day': day
    }
    return render(request, 'diary/day_confirm_delete.html', context)


def detail(request, pk):
    """
    Itemの詳細
    """
    day = Day.get(str(pk))
    print(day)
    context = {
        'day': day
    }
    return render(request, 'diary/day_detail.html', context)

application/diary/templates/diary/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Diary Application</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light mb-3" style="background-color: #e3f2fd; margin-bottom;">
        <a class="navbar-brand" href="{% url 'diary:index' %}">Diary</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'diary:index' %}">一覧</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'diary:add' %}">追加</a>
            </li>
            {% endif %}
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

    {% block content %}
    {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

application/diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="post">
  <table class="table">
    <tr>
      <th>タイトル</th>
      <td>{{ day.title }}</td>
    </tr>
    <tr>
      <th>本文</th>
      <td>{{ day.text }}</td>
    </tr>
    <tr>
      <th>日付</th>
      <td>{{ day.date }}</td>
    </tr>
  </table>
  <p>こちらのデータを削除しますか？</p>
  <button type="submit" class="btn btn-primary">送信</button>
  {% csrf_token %}
</form>
{% endblock %}

application/diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}

{% block content %}
  <table class="table">
    <tr>
      <th>タイトル</th>
      <td>{{ day.title }}</td>
    </tr>
    <tr>
      <th>本文</th>
      <td>{{ day.text | linebreaksbr }}</td>
    </tr>
    <tr>
      <th>日付</th>
      <td>{{ day.date }}</td>
    </tr>
  </table>
{% endblock %}

application/diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="post">
  <table class="table">
    <tr>
      <th>タイトル</th>
      <td><input type="text" name="title" maxlength="200" required id="id_title" value="{{ day.title }}"></td>
    </tr>
    <tr>
      <th>本文</th>
      <td>
        <textarea name="text" cols="40" rows="10" required id="id_text">{{ day.text }}</textarea>
      </td>
    </tr>
    <tr>
      <th>日付</th>
      <td><input type="text" name="date" id="id_date" value="{{ day.created_at }}"></td>
    </tr>
  </table>
  <button type="submit" class="btn btn-primary">送信</button>
  {% csrf_token %}
</form>
{% endblock %}

application/diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1 class="mb-4">日記一覧</h1>
<table class="table">
  <thred>
    <tr>
      <th>タイトル</th>
      <th>日付</th>
      {% if user.is_superuser %}
      <th>#</th>
      <th>#</th>
      {% endif %}
    </tr>
  </thred>
  <tbody>
    {% for day in day_list %}
    <tr>
      <td><a href="{% url 'diary:detail' day.id %}">{{ day.title }}</a></td>
      <td>{{ day.date }}</td>
      {% if user.is_superuser %}
      <td><a href="{% url 'diary:update' day.id %}">更新</a></td>
      <td><a href="{% url 'diary:delete' day.id %}">削除</a></td>
      {% endif %}
    </tr>
    {% endfor %}
  </tbody>
</table>

{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

{% endblock %}